language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - '$HOME/.m2/'
install: true
script:
  - ./mvnw -s settings.xml -Pprepare-release
  - ./mvnw -s settings.xml -Pbuild-release
  - ./mvnw -s settings.xml -Ppublish-release
branches:
  only:
    - master
notifications:
  slack: grokclimbing:HkisDPAARo7pzk2Ao5O66pg1
git:
  depth: 99999999
