language: java
jdk:
  - oraclejdk8
install: true
script:
  - ./mvnw -s settings.xml -Pprepare-release
  - ./mvnw -s settings.xml -Prelease
branches:
  only:
    - master
notifications:
  slack: grokclimbing:HkisDPAARo7pzk2Ao5O66pg1